#app
spring.application.name=finance

# SQLite
spring.datasource.url=postgresql://finance_db_ejcq_user:e0pqY1HZDnWuP1NoIGClaRC5BuLUiaZM@dpg-d78utjjuibrs73bvphq0-a/finance_db_ejcq
spring.datasource.driver-class-name=org.postgresql.Driver
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true

# JWT
app.jwt.secret=Internship_zorvyn_super_secret_key_2026_make_it_long
app.jwt.expiration=86400000

# Swagger
springdoc.swagger-ui.path=/swagger-ui.html
springdoc.api-docs.path=/v3/api-docs
springdoc.swagger-ui.try-it-out-enabled=true
springdoc.swagger-ui.operations-sorter=method
#
